export { default as About } from "./About/About";
export { default as Contact } from "./Contact/Contact";
export { default as Experience } from "./Experience/Experience";
export { default as Feedbacks } from "./Feedbacks/Feedbacks";
export { default as Hero } from "./Hero/Hero";
export { default as Loader } from "./Loader/Loader";
export { default as Navbar } from "./Navbar/Navbar";
export { default as Tech } from "./Tech/Tech";
export { default as Works } from "./Works/Works";
export * as CanvasComponents from "./canvas";
